# Use the official Node.js as a parent image
FROM node:latest

RUN npm install -g forever

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY tailwind/package*.json ./
COPY app/static/ ../static

# Install dependencies
RUN npm install

# Command to compile CSS and watch for changes
CMD ["npx", "tailwindcss", "-i", "../static/src/input.css", "-o", "../static/src/output.css", "--watch"]